class UserNotFoundError(Exception): ...


class UserAlreadyExistsError(Exception): ...


class InvalidUUIDError(Exception): ...


class ProjectAlreadyExistsError(Exception): ...


class ProjectNotFoundError(Exception): ...
