class UserNotFoundError(Exception): ...


class UserAlreadyExistsError(Exception): ...


class InvalidUUIDError(Exception): ...


class ProjectAlreadyExistsError(Exception): ...


class ProjectNotFoundError(Exception): ...


class RabbitMQServiceUnavailableError(Exception): ...


class FailedToUploadS3FileError(Exception): ...


class FiledToDeleteS3FileError(Exception): ...


class BaseImageValidationError(Exception): ...


class ImageFetchError(BaseImageValidationError): ...


class ImageFormatError(BaseImageValidationError): ...


class ImageSizeError(BaseImageValidationError): ...


class AuthBaseError(Exception): ...


class UnknownBotAuthError(AuthBaseError): ...


class UnsupportedClientTypeError(AuthBaseError): ...


class InvalidSignatureError(AuthBaseError): ...


class InvalidPayloadError(AuthBaseError): ...
