class UserNotFoundError(Exception): ...


class UserAlreadyExistsError(Exception): ...


class InvalidUUIDError(Exception): ...


class ProjectAlreadyExistsError(Exception): ...


class ProjectNotFoundError(Exception): ...


class RabbitMQServiceUnavailableError(Exception): ...


class FailedToUploadS3FileError(Exception): ...


class FiledToDeleteS3FileError(Exception): ...
