from pathlib import Path
from typing import Coroutine, Callable, Any

from fastapi import APIRouter, status, HTTPException, Depends
from fastapi.responses import FileResponse

from core.config import settings

BASE_DIR = Path.cwd().resolve().parent  # project working directory api_atomlab/app
FRONTEND_DIR = (
    (BASE_DIR / "api-frontend") if settings.run.dev_mode else (BASE_DIR / "frontend")
)
HTML_DIR = FRONTEND_DIR / "src"
STATIC_DIR = FRONTEND_DIR / "public"
NOT_FOUND_PAGE_404 = FRONTEND_DIR / "src/404.html"

router = APIRouter()


async def check_path(path_file: Path):
    file_exists = Path(path_file).exists()
    return (
        (
            path_file,
            status.HTTP_200_OK,
        )
        if file_exists
        else (
            NOT_FOUND_PAGE_404,
            status.HTTP_404_NOT_FOUND,
        )
    )


def file_dependency(
    base_dir: Path,
    sub_dir: str | None = None,
) -> Callable[[str], Coroutine[Any, Any, Path]]:
    async def _get_file(
        name_file: str,
    ) -> Path:
        file_path = base_dir / sub_dir / name_file if sub_dir else base_dir / name_file
        if not file_path.exists():
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"File {name_file} not found",
            )
        return file_path

    return _get_file


@router.get("/")
async def index_page():
    """
    Returns the main application HTML file.

    Returns:
        FileResponse: Response object containing the `index.html` file
                      located in the `HTML_DIR` directory.

    Description:
        This endpoint serves as the entry point for the frontend application.
        It constructs the file path as `HTML_DIR / "index.html"`.
    """
    index_html = HTML_DIR / "index.html"
    return FileResponse(index_html)


@router.get(
    "/favicon.ico",
    include_in_schema=False,
)
async def favicon():
    """
    Returns the website's favicon file.

    Returns:
        FileResponse: Response object containing the `favicon.ico` file
                      located in the `STATIC_DIR` directory.
    """
    return FileResponse(STATIC_DIR / "favicon.ico")


@router.get(
    "/robots.txt",
    include_in_schema=settings.run.dev_mode,
)
async def robots():
    """
    Returns the `robots.txt` file for search engine indexing rules.

    Returns:
        FileResponse: The contents of the `robots.txt` file located in the
                      `STATIC_DIR` directory with HTTP 200 OK status.
    """
    return FileResponse(STATIC_DIR / "robots.txt")


@router.get(
    "/html/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_html(
    file_path: Path = Depends(
        file_dependency(
            base_dir=HTML_DIR,
        )
    )
):
    """
    Returns a requested HTML file from the frontend source directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `HTML_DIR` (frontend/src).

    Returns:
        FileResponse: The requested HTML file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )


@router.get(
    "/media/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_media(
    file_path: Path = Depends(
        file_dependency(
            base_dir=STATIC_DIR,
            sub_dir="media",
        )
    )
):
    """
    Returns a requested media file (images, videos, etc.) from the public/media directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `STATIC_DIR`, subdirectory is "media".

    Returns:
        FileResponse: The requested media file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )


@router.get(
    "/style/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_styles(
    file_path: Path = Depends(
        file_dependency(
            base_dir=HTML_DIR,
            sub_dir="style",
        )
    )
):
    """
    Returns a requested CSS file from the frontend style directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `HTML_DIR`, subdirectory is "style".

    Returns:
        FileResponse: The requested CSS file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )


@router.get(
    "/scripts/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_scripts(
    file_path: Path = Depends(
        file_dependency(
            base_dir=HTML_DIR,
            sub_dir="scripts",
        )
    )
):
    """
    Returns a requested JavaScript file from the frontend scripts directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `HTML_DIR`, subdirectory is "scripts".

    Returns:
        FileResponse: The requested JavaScript file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )
