from pathlib import Path

from fastapi import APIRouter, status, Depends
from fastapi.responses import FileResponse

from api.api_v2.dependencies import SRC_DIR, PUBLIC_DIR, file_dependency
from core.config import settings

router = APIRouter()


@router.get("/")
async def index_page() -> FileResponse:
    """
    Returns the main application HTML file.

    Returns:
        FileResponse: Response object containing the `index.html` file
                      located in the `HTML_DIR` directory.

    Description:
        This endpoint serves as the entry point for the frontend application.
        It constructs the file path as `HTML_DIR / "index.html"`.
    """
    index_html = SRC_DIR / "index.html"
    return FileResponse(index_html)


@router.get(
    "/favicon.ico",
    include_in_schema=False,
)
async def favicon() -> FileResponse:
    """
    Returns the website's favicon file.

    Returns:
        FileResponse: Response object containing the `favicon.ico` file
                      located in the `STATIC_DIR` directory.
    """
    return FileResponse(PUBLIC_DIR / "favicon.ico")


@router.get(
    "/robots.txt",
    include_in_schema=settings.run.dev_mode,
)
async def robots() -> FileResponse:
    """
    Returns the `robots.txt` file for search engine indexing rules.

    Returns:
        FileResponse: The contents of the `robots.txt` file located in the
                      `STATIC_DIR` directory with HTTP 200 OK status.
    """
    return FileResponse(PUBLIC_DIR / "robots.txt")


@router.get(
    "/html/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_html(
    file_path: Path = Depends(
        file_dependency(
            base_dir=SRC_DIR,
        )
    )
) -> FileResponse:
    """
    Returns a requested HTML file from the frontend source directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `HTML_DIR` (frontend/src).

    Returns:
        FileResponse: The requested HTML file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )


@router.get(
    "/media/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_media(
    file_path: Path = Depends(
        file_dependency(
            base_dir=PUBLIC_DIR,
            sub_dir="media",
        )
    )
) -> FileResponse:
    """
    Returns a requested media file (images, videos, etc.) from the public/media directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `STATIC_DIR`, subdirectory is "media".

    Returns:
        FileResponse: The requested media file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )


@router.get(
    "/style/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_styles(
    file_path: Path = Depends(
        file_dependency(
            base_dir=SRC_DIR,
            sub_dir="style",
        )
    )
) -> FileResponse:
    """
    Returns a requested CSS file from the frontend style directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `HTML_DIR`, subdirectory is "style".

    Returns:
        FileResponse: The requested CSS file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )


@router.get(
    "/scripts/{name_file}",
    include_in_schema=settings.run.dev_mode,
)
async def get_static_scripts(
    file_path: Path = Depends(
        file_dependency(
            base_dir=SRC_DIR,
            sub_dir="scripts",
        )
    )
) -> FileResponse:
    """
    Returns a requested JavaScript file from the frontend scripts directory.

    Args:
        file_path (Path): Resolved file path generated by `file_dependency`.
                          Base directory is `HTML_DIR`, subdirectory is "scripts".

    Returns:
        FileResponse: The requested JavaScript file with HTTP 200 OK status.
    """
    return FileResponse(
        file_path,
        status_code=status.HTTP_200_OK,
    )
